### PR TITLE
Virials in C interface and docs

### PR DESCRIPTION
**Pull request by fefiedler**

### CODE REVIEW

**Comment by ianhbell** [comment]
I don't really see what happened here, but the changes to the C interface don't appear in the list of file changes, only the change to the docs, which I don't even think is relevant here. Can you try to update your fork to equal the teqp master, add your change in a branch, and make a new PR with the brach?

**Comment by fefiedler** [comment]
Okay, I am also a bit confused by this doc file. I will make a branch and try to another PR.

**Comment by ianhbell** [comment]
Do you want me to grab your virial function from your code and stick it in teqp? I am inclined to keep the same name as the C++ function it wraps if that is ok with you.

**Comment by fefiedler** [comment]
Yes, that would help a lot. Thank you!

**Comment by ianhbell** [comment]
I am super confused now. The commit with the virials is already in teqp (although I am going to change the name to match the C++ function to keep things clear). I think this PR needs to be closed.

**Pull request closed without merging**
